site_name: Tales of the family
site_description: Tales of the family - Bourne's rebels and other stories
site_url: https://cullaloe.com/family/
site_author: Nick Hood
docs_dir: source
site_dir: docs
repo_url: https://github.com/NixImagery
repo_name: family
edit_uri: ""
copyright: Copyright &copy; 1976 - 2025 Nick Hood

theme:
  name: material
  custom_dir: overrides
  favicon: img/NRH-avatar.png
  logo: img/anarchysm.gif
  features:
    - navigation.instant
    - navigation.indexes
    - toc.integrate
    # - navigation.tabs
    # - navigation.sections

  palette:
    scheme: family
extra_css:
  - stylesheets/extra.css

nav: 
  - Home: index.md
  - Bourne: Bourne/
  - Hood/Straight: Hood/
  - Index: 'tags.md'

plugins: 
  - search
  - glightbox
  - literate-nav
  - tags:
      tags_file: tags.md
  - git-revision-date-localized

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - footnotes
  - admonition
  - meta
  - toc:
      title: On this page

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/NixImagery
      name: The NixImagery Repository at GitHub
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/niximagery/
      name: NixImagery on Instagram
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.scot/@niximagery
      name: NixImagery on Mastodon
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/NixImagery
      name: NixImagery on Twitter

  analytics:
    provider: google
    property: G-SBDYJL4PWN
